### ISSUE TITLE
v1.4c File client\preInit.sqf [A3W_fnc_preInit], line 1

### ISSUE THREAD

**Issue by 1datatec** [A3Wasteland/ArmA3_Wasteland.Malden#2]
19:25:54 Error in expression <enableChannel false;disableMapIndicators[true,true,true,false];0 spawn{waitUntil>
19:25:54   Error position: <[true,true,true,false];0 spawn{waitUntil>
19:25:54   Error Missing ;
19:25:54 File client\preInit.sqf [A3W_fnc_preInit], line 1
19:25:54 Error in expression <enableChannel false;disableMapIndicators[true,true,true,false];0 spawn{waitUntil>
19:25:54   Error position: <[true,true,true,false];0 spawn{waitUntil>
19:25:54   Error Missing ;
19:25:54 File client\preInit.sqf [A3W_fnc_preInit], line 1

https://pastebin.com/heEMA5y4

commenting out disableMapIndicators fixes it

**Comment by AgentRev** [comment]
You are not supposed to deploy this update until the Tanks DLC is released tomorrow. This is a new command introduced in A3 v1.82.

**Comment by 1datatec** [comment]
Yeah i just noticed that steamcmd 233780 -beta development didn't install the beta server for some reason.
Preparing :)

**Comment by 1datatec** [comment]
All good.
