### ISSUE TITLE
1.4c vehicleCreation.sqf, line 61

### ISSUE THREAD

**Issue by 1datatec** [A3Wasteland/ArmA3_Wasteland.Malden#3]
20:53:32 Error in expression <ms ["_mag", "_path", "_ammo"];
_vehicle setMagazineTurretAmmo [_mag, _path, floo>
20:53:32   Error position: <setMagazineTurretAmmo [_mag, _path, floo>
20:53:32   Error Type Array, expected Number
20:53:32 File mpmissions\__cur_mp.Malden\server\spawning\vehicleCreation.sqf, line 61

The file is exactly like on your github. Where do i dig?
It's about `if (_vehicleType isKindOf "Offroad_01_AT_base_F") then` as i understand

**Comment by AgentRev** [comment]
Oops I didn't test that file, the correct syntax is

    _vehicle setMagazineTurretAmmo [_mag, floor random 3, _path];

**Comment by 1datatec** [comment]
Ok i just converted my malden server to 1.4c, didn't see anything erroring in logs. Good job!!!
p.s. Stratis also ;)
